cookie:
  expiry_days: 30
  key: audio_fake_detec_app_key
  name: audio_fake_detec_cookie
credentials:
  usernames:
    art456:
      email: artur@gmail.com
      failed_login_attempts: 0
      first_name: Artur
      last_name: C Boaventura
      logged_in: false
      password: $2b$12$arkl/TPy/zb84S7dEWL/beL0T0JcWr70u.bXlTywpGGhBicQCgY1y
      password_hint: Aa12345$
      roles: null
    lakhamote:
      email: lucas@gmail.com
      failed_login_attempts: 0
      first_name: Lucas
      last_name: C. Boaventura
      logged_in: true
      password: $2b$12$AzZsdnvH5Qpflf/H.U/RNegg2p81HTieiJaoDjzRhD.c.4RelQRUS
      password_hint: Ll12345$
      roles:
      - admin
    vidal:
      email: vidal@gmail.com
      failed_login_attempts: 0
      first_name: Flavio
      last_name: Vidal
      logged_in: false
      password: $2b$12$Et0SGMlc.Aa77KupZFao1eddm6oSAq0OMcuRzKRw45xz9StTIZ0aa
      password_hint: '12345'
      roles:
      - admin
