services:
  app:
    build: .
    ports:
      - "443:8501"
    volumes:
      - .:/app
      - ~/.cache/torch/hub:/root/.cache/torch/hub # Cache of all weights to  avoid re-downloading
      - ../dataset/mel-image-ljspeech-and-wavefake:/dataset-test
      - ./components/VoCoderRecognition/dataset/generated/spec:/dataset # Dataset for training
      # - ./seu_dataset:/dataset  # Mounts the dataset directory
    environment:
      - STREAMLIT_SERVER_PORT=8501
    runtime: nvidia  #GPU support
